import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import SlidebarComponent from "@/libraries/components/slidebar/slidebar-component";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import FooterPlayerComponent from "@/libraries/components/footer-player/footer-player-component";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Stringify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-[100vh] relative flex-col">
          <AppRouterCacheProvider>
            <div className="flex-col h-full">
              <div className="flex p-4 flex-1 h-[92vh]">
                <SlidebarComponent />
                <div className="rounded-md bg-slight-gray w-[400px] flex-1">
                  {children}
                </div>
              </div>
              <FooterPlayerComponent />
            </div>
          </AppRouterCacheProvider>
        </div>
      </body>
    </html>
  );
}
